# Jupyter Book configuration
title: "Python Course Theory"
only_build_toc_files: true

execute:
  execute_notebooks: auto   # "auto" runs if outputs are missing, "off" skips execution

html:
  favicon: ""
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false

sphinx:
  config:
    html_extra_path:
      - images/